### PR TITLE
Fixed column names and gulp task update-manifest

### PR DESCRIPTION
**Pull request by LukasNespor**

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi Lukáš,
Thanks for your contribution. We will evaluate this PR in the upcoming days.

**Comment by PerOve** [comment]
Great fix, exactly what I had to do as well to get the gulp tasks running,
Did not know about the column fix, So i will do that manually as well

**Comment by PaoloPia** [comment]
Hi @LukasNespor and @PerOve,
Can you kindly explain the purpose of the fix to the column name? Thanks.

**Comment by LukasNespor** [comment]
Hi @PaoloPia,
there were wrong FieldRef eg. on [L1478](https://github.com/SharePoint/sp-dev-gdpr-activity-hub/pull/4/files#diff-802fb04d64ead54776feeba47f0656a7L1478) was "Description" but there is no field with intenal name "Description". The correct one is "Body" which is defined on [L1488](https://github.com/LukasNespor/sp-dev-gdpr-activity-hub/blob/60996847c460868fc6a636d416550fec4841c8ac/Scripts/GDPR-Activity-Hub-Information-Architecture-Full.xml#L1488)

**Comment by PaoloPia** [comment]
Hi,
I still don't get completely the fix, because what we have right now is working on a lot of tenants. I'm just wondering, are you eventually using a specific language for your target site?

**Comment by LukasNespor** [comment]
Hi,
I found where is the issue :) I was fixing master branch where this column mismatch is, but it was already fixed in dev branch. Change in GDPR-Activity-Hub-Information-Architecture-Full.xml is than useless.

**Comment by biste5** [comment]
Also, I think would be better to reference 'gulpfile-update-manifest.js' from 'gulpfile.js', as in this documentation page
https://github.com/SharePoint/sp-dev-build-extensions/tree/master/gulp-tasks/update-manifest

Result is the same, but seen we have a separate file already, it would have been easier/better.

Reference: #22

**Comment by PaoloPia** [comment]
Ok, based on the comments above and on the fact that there are other PRs that fix these issues, I will close this item. Thanks for your contribution.

**Pull request closed without merging**
